### ISSUE TITLE
Enter to login

### ISSUE THREAD

**Issue by CDuPlooy** [3ximus/abstractdark-sddm-theme#1]
It would seem that typing a password and tapping enter does not work , I'll check again just to make sure but if this is missing could you please add it ? I'm using a minimal setup with i3 and arch ; and this theme is perfect for it!

**Comment by CDuPlooy** [comment]
Nevermind , it would seem my laptop was misbehaving. I'll change my comment , this theme is perfect :) :+1:

**Comment by 3ximus** [comment]
Thanks :)
